# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio03' do
  # Flexbox Layout Manager Used By React Natve
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for desafio03

  #target 'desafio03-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  #end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'desafio03Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'desafio03-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for desafio03-tvOS

  target 'desafio03-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
